import { Aviation } from "../structures";

const aviation: Aviation[] = [
    {
        "slug": "air-peace",
        "name": "AIR PEACE",
        "company_name": "AIR PEACE LIMITED",
        "logo": "https://flyairpeace.com/image/logo2x.png",
        "details": "Air Peace is a private Nigerian airline based in Lagos. It has a subsidiary, Air peace hopper, which was founded in 2018 and is used for smaller domestic and regional routes in Nigeria. It serves all major cities of Nigeria, as well as flying to several West African destinations and the middle west.",
        "routes": [
            { "origin": "ASABA(ABB)", "destination": "ABUJA (ABV)" },
            { "origin": "ASABA(ABB)", "destination": "ACCRA (ACC)" },
            { "origin": "ASABA(ABB)", "destination": "BANJUL(BJL)" },
            { "origin": "ASABA(ABB)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ASABA(ABB)", "destination": "FREETOWN (FNA)" },
            { "origin": "ASABA(ABB)", "destination": "LAGOS (LOS)" },
            { "origin": "ASABA(ABB)", "destination": "LONDON-GATWICK SOUTH TERMINAL (LGW)" },
            { "origin": "ASABA(ABB)", "destination": "MONROVIA (ROB)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "COTONOU (COO)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "LAGOS(LOS)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "LONDON-GATWICK SOUTH TERMINAL (LGW)" },
            { "origin": "ABUJA(ABV)", "destination": "ASABA(ABB)" },
            { "origin": "ABUJA(ABV)", "destination": "ACCRA (ACC)" },
            { "origin": "ABUJA(ABV)", "destination": "AKURE(AKR)" },
            { "origin": "ABUJA(ABV)", "destination": "ANAMBRA(ANA)" },
            { "origin": "ABUJA(ABV)", "destination": "BANJUL(BJL)" },
            { "origin": "ABUJA(ABV)", "destination": "BENINCITY(BNI)" },
            { "origin": "ABUJA(ABV)", "destination": "CALABAR(CBQ)" },
            { "origin": "ABUJA(ABV)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ABUJA(ABV)", "destination": "DOUALA(DLA)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "FREETOWN(FNA)" },
            { "origin": "ABUJA(ABV)", "destination": "GOMBE(GMO)" },
            { "origin": "ABUJA(ABV)", "destination": "IBADAN(IBA)" },
            { "origin": "ABUJA(ABV)", "destination": "ILORIN(ILR)" },
            { "origin": "ABUJA(ABV)", "destination": "JEDDAH (JED)" },
            { "origin": "ABUJA(ABV)", "destination": "JOHANNESBURG(JNB)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "ABUJA(ABV)", "destination": "LONDON-GATWICK SOUTH TERMINAL (LGW)" },
            { "origin": "ABUJA(ABV)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "ABUJA(ABV)", "destination": "MAKURDI(MDI)" },
            { "origin": "ABUJA(ABV)", "destination": "MONROVIA(ROB)" },
            { "origin": "ABUJA(ABV)", "destination": "OWEERI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "ABUJA(ABV)", "destination": "UYO(QUO)" },
            { "origin": "ABUJA(ABV)", "destination": "WARRI(QRW)" },
            { "origin": "ABUJA(ABV)", "destination": "YOLA(YOL)" },
            { "origin": "ACCRA(ACC)", "destination": "ASABA(ABB)" },
            { "origin": "ACCRA(ACC)", "destination": "ABUJA(ABV)" },
            { "origin": "ACCRA(ACC)", "destination": "BANJUL(BJL)" },
            { "origin": "ACCRA(ACC)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ACCRA(ACC)", "destination": "FREETOWN(FNA)" },
            { "origin": "ACCRA(ACC)", "destination": "LAGOS(LOS)" },
            { "origin": "ACCRA(ACC)", "destination": "LONDON-GATWICK SOUTH TERMINAL(LGW)" },
            { "origin": "ACCRA(ACC)", "destination": "MONROVIA(ROB)" },
            { "origin": "ACCRA(ACC)", "destination": "RIO DE JANEIRO (RIO)" },
            { "origin": "ACCRA(ACC)", "destination": "SAO PAULO (SAO)" },
            { "origin": "ACCRA(ACC)", "destination": "TAKORADI(TKD)" },
            { "origin": "ACCRA(ACC)", "destination": "TAMALE(TML)" },
            { "origin": "ACCRA(ACC)", "destination": "WA (WZA)" },
            { "origin": "ACCRA(ACC)", "destination": "CAPE COAST(COC)" },
            { "origin": "BANJUL(BJL)", "destination": "ASABA(ABB)" },
            { "origin": "BANJUL(BJL)", "destination": "ABUJA(ABV)" },
            { "origin": "BANJUL(BJL)", "destination": "ACCRA(ACC)" },
            { "origin": "BANJUL(BJL)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "BANJUL(BJL)", "destination": "FREETOWN(FNA)" },
            { "origin": "BANJUL(BJL)", "destination": "LAGOS(LOS)" },
            { "origin": "BANJUL(BJL)", "destination": "LONDON-GATWICK SOUTH TERMINAL(LGW)" },
            { "origin": "BANJUL(BJL)", "destination": "MONROVIA(ROB)" },
            { "origin": "BANJUL(BJL)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "BANJUL(BJL)", "destination": "FREETOWN(FNA)" },
            { "origin": "BANJUL(BJL)", "destination": "LAGOS(LOS)" },
            { "origin": "BANJUL(BJL)", "destination": "LONDON-GATWICK SOUTH TERMINAL(LGW)" }
        ],
        "searchDump": JSON.stringify([
            { "origin": "ASABA(ABB)", "destination": "ABUJA (ABV)" },
            { "origin": "ASABA(ABB)", "destination": "ACCRA (ACC)" },
            { "origin": "ASABA(ABB)", "destination": "BANJUL(BJL)" },
            { "origin": "ASABA(ABB)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ASABA(ABB)", "destination": "FREETOWN (FNA)" },
            { "origin": "ASABA(ABB)", "destination": "LAGOS (LOS)" },
            { "origin": "ASABA(ABB)", "destination": "LONDON-GATWICK SOUTH TERMINAL (LGW)" },
            { "origin": "ASABA(ABB)", "destination": "MONROVIA (ROB)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "COTONOU (COO)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "LAGOS(LOS)" },
            { "origin": "ABIDJAN(ABJ)", "destination": "LONDON-GATWICK SOUTH TERMINAL (LGW)" },
            { "origin": "ABUJA(ABV)", "destination": "ASABA(ABB)" },
            { "origin": "ABUJA(ABV)", "destination": "ACCRA (ACC)" },
            { "origin": "ABUJA(ABV)", "destination": "AKURE(AKR)" },
            { "origin": "ABUJA(ABV)", "destination": "ANAMBRA(ANA)" },
            { "origin": "ABUJA(ABV)", "destination": "BANJUL(BJL)" },
            { "origin": "ABUJA(ABV)", "destination": "BENINCITY(BNI)" },
            { "origin": "ABUJA(ABV)", "destination": "CALABAR(CBQ)" },
            { "origin": "ABUJA(ABV)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ABUJA(ABV)", "destination": "DOUALA(DLA)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "FREETOWN(FNA)" },
            { "origin": "ABUJA(ABV)", "destination": "GOMBE(GMO)" },
            { "origin": "ABUJA(ABV)", "destination": "IBADAN(IBA)" },
            { "origin": "ABUJA(ABV)", "destination": "ILORIN(ILR)" },
            { "origin": "ABUJA(ABV)", "destination": "JEDDAH (JED)" },
            { "origin": "ABUJA(ABV)", "destination": "JOHANNESBURG(JNB)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "ABUJA(ABV)", "destination": "LONDON-GATWICK SOUTH TERMINAL (LGW)" },
            { "origin": "ABUJA(ABV)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "ABUJA(ABV)", "destination": "MAKURDI(MDI)" },
            { "origin": "ABUJA(ABV)", "destination": "MONROVIA(ROB)" },
            { "origin": "ABUJA(ABV)", "destination": "OWEERI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "ABUJA(ABV)", "destination": "UYO(QUO)" },
            { "origin": "ABUJA(ABV)", "destination": "WARRI(QRW)" },
            { "origin": "ABUJA(ABV)", "destination": "YOLA(YOL)" },
            { "origin": "ACCRA(ACC)", "destination": "ASABA(ABB)" },
            { "origin": "ACCRA(ACC)", "destination": "ABUJA(ABV)" },
            { "origin": "ACCRA(ACC)", "destination": "BANJUL(BJL)" },
            { "origin": "ACCRA(ACC)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "ACCRA(ACC)", "destination": "FREETOWN(FNA)" },
            { "origin": "ACCRA(ACC)", "destination": "LAGOS(LOS)" },
            { "origin": "ACCRA(ACC)", "destination": "LONDON-GATWICK SOUTH TERMINAL(LGW)" },
            { "origin": "ACCRA(ACC)", "destination": "MONROVIA(ROB)" },
            { "origin": "ACCRA(ACC)", "destination": "RIO DE JANEIRO (RIO)" },
            { "origin": "ACCRA(ACC)", "destination": "SAO PAULO (SAO)" },
            { "origin": "ACCRA(ACC)", "destination": "TAKORADI(TKD)" },
            { "origin": "ACCRA(ACC)", "destination": "TAMALE(TML)" },
            { "origin": "ACCRA(ACC)", "destination": "WA (WZA)" },
            { "origin": "ACCRA(ACC)", "destination": "CAPE COAST(COC)" },
            { "origin": "BANJUL(BJL)", "destination": "ASABA(ABB)" },
            { "origin": "BANJUL(BJL)", "destination": "ABUJA(ABV)" },
            { "origin": "BANJUL(BJL)", "destination": "ACCRA(ACC)" },
            { "origin": "BANJUL(BJL)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "BANJUL(BJL)", "destination": "FREETOWN(FNA)" },
            { "origin": "BANJUL(BJL)", "destination": "LAGOS(LOS)" },
            { "origin": "BANJUL(BJL)", "destination": "LONDON-GATWICK SOUTH TERMINAL(LGW)" },
            { "origin": "BANJUL(BJL)", "destination": "MONROVIA(ROB)" },
            { "origin": "BANJUL(BJL)", "destination": "DAKAR BLAISE DIAGNE INTERNATIO (DSS)" },
            { "origin": "BANJUL(BJL)", "destination": "FREETOWN(FNA)" },
            { "origin": "BANJUL(BJL)", "destination": "LAGOS(LOS)" },
            { "origin": "BANJUL(BJL)", "destination": "LONDON-GATWICK SOUTH TERMINAL(LGW)" },
            {
                "keywords": [
                    "airpeace",
                    "flyairpeace",
                ]
            }
        ]),
        "link": "www.flyairpeace.com",
        "fleet_size": 30,
        "headoffice": "25, Sobo Arobiodu Street GRA, Ikeja, Lagos, Nigeria",
        "hubs": ["Lagos"],
        "base": "Murtala Muhammed International Airport, Lagos"
    },
    {
        "slug": "arik-air",
        "name": "ARIK AIR",
        "company_name": "ARIK AIR INTERNATIONAL LIMITED",
        "logo": "https://www.arikair.com/assets/images/logo.png",
        "details": "Arik Air is a privately and wholly Nigerian owned commercial airline operating both domestic and international flights. It started operations in 2006 and is West Africa's leading airline. Its head office is at Arik Air Aviation Center on the grounds of Murtala Muhammed International Airport in Ikeja, Lagos State.",
        "routes": [
            { "origin": "Lagos(LOS)", "destination": "Abuja(ABV)" },
            { "origin": "Lagos(LOS)", "destination": "Benin City(BNI)" },
            { "origin": "Lagos(LOS)", "destination": "Jos(JOS)" },
            { "origin": "Lagos(LOS)", "destination": "Port Harcourt Int'l(PHC)" },
            { "origin": "Lagos(LOS)", "destination": "Sokoto(SKO)" },
            { "origin": "Lagos(LOS)", "destination": "Warri(QRW)" },
            { "origin": "Lagos(LOS)", "destination": "Yola(YOL)" },
            { "origin": "Abuja(ABV)", "destination": "Lagos(LOS)" },
            { "origin": "Abuja(ABV)", "destination": "Benin City(BNI)" },
            { "origin": "Abuja(ABV)", "destination": "Sokoto(SKO)" },
            { "origin": "Abuja(ABV)", "destination": "Yola(YOL)" },
            { "origin": "Benin City(BNI)", "destination": "Lagos(LOS)" },
            { "origin": "Benin City(BNI)", "destination": "Abuja(ABV)" },
            { "origin": "Jos(JOS)", "destination": "Lagos(LOS)" },
            { "origin": "Port Harcourt Int'l(PHC)", "destination": "Lagos(LOS)" },
            { "origin": "Sokoto(SKO)", "destination": "Lagos(LOS)" },
            { "origin": "Sokoto(SKO)", "destination": "Abuja(ABJ)" },
            { "origin": "Warri(QRW)", "destination": "Lagos(LOS)" },
            { "origin": "Yola(YOL)", "destination": "Lagos(LOS)" },
            { "origin": "Yola(YOL)", "destination": "Abuja(ABV)" }
        ],
        "searchDump": JSON.stringify([{ "origin": "Lagos(LOS)", "destination": "Abuja(ABV)" },
        { "origin": "Lagos(LOS)", "destination": "Benin City(BNI)" },
        { "origin": "Lagos(LOS)", "destination": "Jos(JOS)" },
        { "origin": "Lagos(LOS)", "destination": "Port Harcourt Int'l(PHC)" },
        { "origin": "Lagos(LOS)", "destination": "Sokoto(SKO)" },
        { "origin": "Lagos(LOS)", "destination": "Warri(QRW)" },
        { "origin": "Lagos(LOS)", "destination": "Yola(YOL)" },
        { "origin": "Abuja(ABV)", "destination": "Lagos(LOS)" },
        { "origin": "Abuja(ABV)", "destination": "Benin City(BNI)" },
        { "origin": "Abuja(ABV)", "destination": "Sokoto(SKO)" },
        { "origin": "Abuja(ABV)", "destination": "Yola(YOL)" },
        { "origin": "Benin City(BNI)", "destination": "Lagos(LOS)" },
        { "origin": "Benin City(BNI)", "destination": "Abuja(ABV)" },
        { "origin": "Jos(JOS)", "destination": "Lagos(LOS)" },
        { "origin": "Port Harcourt Int'l(PHC)", "destination": "Lagos(LOS)" },
        { "origin": "Sokoto(SKO)", "destination": "Lagos(LOS)" },
        { "origin": "Sokoto(SKO)", "destination": "Abuja(ABJ)" },
        { "origin": "Warri(QRW)", "destination": "Lagos(LOS)" },
        { "origin": "Yola(YOL)", "destination": "Lagos(LOS)" },
        { "origin": "Yola(YOL)", "destination": "Abuja(ABV)" }]),
        "link": "www.arikair.com",
        "fleet_size": 14,
        "headoffice": "Arik Air Aviation Center, Murtala Muhammed International Airport, Ikeja, Lagos State, Nigeria",
        "hubs": ["Murtala Muhammed International Airport", "Lagos and Nnamdi Azikiwe International Airport, Abuja"]
    },
    {
        "name": "AZMAN AIR",
        "slug": "azman-air",
        "company_name": "AZMAN AIR SERVICES LIMITED",
        "logo": "https://www.airazman.com/Background%20and%20LOGO/New%20Logo%20-%20Azman%20Air.png",
        "details": "Azman Air is a privately owned airline, based at Kano, at Mallam Aminu Kano International Airport.",
        "routes": [
            { "origin": "ABUJA(ABV)", "destination": "GOMBE(GMO)" },
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "KANO(KAN)", "destination": "" },
            { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "GOMBE(GMO)" },
            { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" }
        ],
        "searchDump": JSON.stringify([{ "origin": "ABUJA(ABV)", "destination": "GOMBE(GMO)" },
        { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
        { "origin": "KANO(KAN)", "destination": "" },
        { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
        { "origin": "KANO(KAN)", "destination": "GOMBE(GMO)" },
        { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
        { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" }]),
        "link": "airazman.com",
        "fleet_size": 5,
        "hubs": ["Mallam Aminu Kano International Airport"]
    },
    {
        "name": "AERO CONTRACTORS",
        "slug": "aero-contractors",
        "company_name": "AEROCONTRACTORS COMPANY OF NIGERIA LIMITED",
        "logo": "https://www.flyaero.com/asset/img/logo.png",
        "details": "Aero contractors known locally as 'AERO', is a state-owned Nigerian airline, based at Murtala Muhammed International Airport. It serves Ikeja, the capital of Lagos State.",
        "routes": [
            { "origin": "ABUJA(ABV)", "destination": "BENIN(BNI)" },
            { "origin": "ABUJA(ABV)", "destination": "CALABAR(CBQ)" },
            { "origin": "ABUJA(ABV)", "destination": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)" },
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "ABUJA(ABV)", "destination": "SOKOTO(SKO)" },
            { "origin": "ABUJA(ABV)", "destination": "YOLA(YOL)" },
            { "origin": "ASABA(ABB)", "destination": "LAGOS(LOS)" },
            { "origin": "BENIN(BNI)", "destination": "ABUJA(ABV)" },
            { "origin": "BENIN(BNI)", "destination": "LAGOS(LOS)" },
            { "origin": "CALABAR(CBQ)", "destination": "ABUJA(ABV)" },
            { "origin": "CALABAR(CBQ)", "destination": "LAGOS(LOS)" },
            { "origin": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)", "destination": "ABUJA(ABV)" },
            { "origin": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)", "destination": "YAKUBU GOWON AIRPORT(JOS)" },
            { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "ASABA(ABB)" },
            { "origin": "LAGOS(LOS)", "destination": "BENIN(BNI)" },
            { "origin": "LAGOS(LOS)", "destination": "CALABAR(CBQ)" },
            { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" },
            { "origin": "LAGOS(LOS)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "SOKOTO(SKO)" },
            { "origin": "LAGOS(LOS)", "destination": "YOLA(YOL)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "SOKOTO(SKO)", "destination": "ABUJA(ABV)" },
            { "origin": "SOKOTO(SKO)", "destination": "LAGOS(LOS)" },
            { "origin": "YAKUBU GOWON AIRPORT(JOS)", "destination": "ABUJA(ABV)" },
            { "origin": "YAKUBU GOWON AIRPORT(JOS)", "destination": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)" },
            { "origin": "YOLA(YOL)", "destination": "ABUJA(ABV)" },
            { "origin": "YOLA(YOL)", "destination": "LAGOS(LOS)" }
        ],
        "link": "flyaero.com",
        "searchDump": JSON.stringify([{ "origin": "ABUJA(ABV)", "destination": "BENIN(BNI)" },
        { "origin": "ABUJA(ABV)", "destination": "CALABAR(CBQ)" },
        { "origin": "ABUJA(ABV)", "destination": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)" },
        { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
        { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
        { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
        { "origin": "ABUJA(ABV)", "destination": "SOKOTO(SKO)" },
        { "origin": "ABUJA(ABV)", "destination": "YOLA(YOL)" },
        { "origin": "ASABA(ABB)", "destination": "LAGOS(LOS)" },
        { "origin": "BENIN(BNI)", "destination": "ABUJA(ABV)" },
        { "origin": "BENIN(BNI)", "destination": "LAGOS(LOS)" },
        { "origin": "CALABAR(CBQ)", "destination": "ABUJA(ABV)" },
        { "origin": "CALABAR(CBQ)", "destination": "LAGOS(LOS)" },
        { "origin": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)", "destination": "ABUJA(ABV)" },
        { "origin": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)", "destination": "YAKUBU GOWON AIRPORT(JOS)" },
        { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
        { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
        { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
        { "origin": "LAGOS(LOS)", "destination": "ASABA(ABB)" },
        { "origin": "LAGOS(LOS)", "destination": "BENIN(BNI)" },
        { "origin": "LAGOS(LOS)", "destination": "CALABAR(CBQ)" },
        { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" },
        { "origin": "LAGOS(LOS)", "destination": "PORTHARCOURT(PHC)" },
        { "origin": "LAGOS(LOS)", "destination": "SOKOTO(SKO)" },
        { "origin": "LAGOS(LOS)", "destination": "YOLA(YOL)" },
        { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
        { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
        { "origin": "SOKOTO(SKO)", "destination": "ABUJA(ABV)" },
        { "origin": "SOKOTO(SKO)", "destination": "LAGOS(LOS)" },
        { "origin": "YAKUBU GOWON AIRPORT(JOS)", "destination": "ABUJA(ABV)" },
        { "origin": "YAKUBU GOWON AIRPORT(JOS)", "destination": "GOMBE LAWANTI INTERNATIONAL AIRPORT(GMO)" },
        { "origin": "YOLA(YOL)", "destination": "ABUJA(ABV)" },
        { "origin": "YOLA(YOL)", "destination": "LAGOS(LOS)" }]),
        "fleet_size": 7,
        "hubs": [
            "Murtala Muhammed International Airport, Lagos",
            "Nnamdi Azikiwe International Airport, Abuja"
        ]
    },
    {
        "name": "DANA AIR",
        "slug": "dana-air",
        "company_name": "DANA AIRLINES LIMITED",
        "logo": "https://flydanaair.com/wp-content/uploads/2023/08/dana-air-logo-1-1536x338.png",
        "details": "Dana Air is a small Nigerian airline headquartered in Ikeja, at Lagos Murtala Muhammed International Airport.",
        "routes": [
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "OWERRI(QOW)" },
            { "origin": "ENUGU(ENU)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
            { "origin": "LAGOS(LOS)", "destination": "OWERRI(QOW)" },
            { "origin": "LAGOS(LOS)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "OWERRI(QOW)", "destination": "ABUAJ(ABV)" },
            { "origin": "OWERRI(QOW)", "destination": "ENUGU(ENU)" },
            { "origin": "OWERRI(QOW)", "destination": "LAGOS(LOS)" },
            { "origin": "OWERRI(QOW)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "ENUGU(ENU)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "OWERRI(QOW)" }
        ],
        "searchDump": JSON.stringify([{ "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
        { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
        { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
        { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
        { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
        { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
        { "origin": "ENUGU(ENU)", "destination": "OWERRI(QOW)" },
        { "origin": "ENUGU(ENU)", "destination": "PORTHARCOURT(PHC)" },
        { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
        { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
        { "origin": "LAGOS(LOS)", "destination": "OWERRI(QOW)" },
        { "origin": "LAGOS(LOS)", "destination": "PORTHARCOURT(PHC)" },
        { "origin": "OWERRI(QOW)", "destination": "ABUAJ(ABV)" },
        { "origin": "OWERRI(QOW)", "destination": "ENUGU(ENU)" },
        { "origin": "OWERRI(QOW)", "destination": "LAGOS(LOS)" },
        { "origin": "OWERRI(QOW)", "destination": "PORTHARCOURT(PHC)" },
        { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
        { "origin": "PORTHARCOURT(PHC)", "destination": "ENUGU(ENU)" },
        { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
        { "origin": "PORTHARCOURT(PHC)", "destination": "OWERRI(QOW)" }]),
        "link": "flydanaair.com",
        "fleet_size": 8,
        "hubs": ["Murtala Muhammed International Airport, Lagos."]
    },
    {
        "name": "MAX AIR",
        "slug": "max-air",
        "company_name": "MAX AIR LIMITED",
        "logo": "https://upload.wikimedia.org/wikipedia/en/thumb/b/bc/Max_Air_logo.jpg/400px-Max_Air_logo.jpg",
        "details": "Max Air is a Nigerian-based airline in Kano, Nigeria. It is the country's longest-serving international airline.",
        "routes": [
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "ABUJA(ABV)", "destination": "KATSINA(DKA)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "SOKOTO(SKO)" },
            { "origin": "ABUJA(ABV)", "destination": "YOLA(YOL)" },
            { "origin": "JEDDAH(JED)", "destination": "KANO(KAN)" },
            { "origin": "JEDDAH(JED)", "destination": "SOKOTO(SKO)" },
            { "origin": "JEDDAH(JED)", "destination": "YOLA(YOL)" },
            { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "JEDDAH(JED)" },
            { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
            { "origin": "KANO(KAN)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "KANO(KAN)", "destination": "OWERRI(QOW)" },
            { "origin": "KANO(KAN)", "destination": "SOKOTO(SKO)" },
            { "origin": "KANO(KAN)", "destination": "YOLA(YOL)" },
            { "origin": "KATSINA(DKA)", "destination": "ABUJA(ABV)" },
            { "origin": "KATSINA(DKA)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" },
            { "origin": "LAGOS(LOS)", "destination": "KATSINA(DKA)" },
            { "origin": "LAGOS(LOS)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "LAGOS(LOS)", "destination": "SOKOTO(SKO)" },
            { "origin": "LAGOS(LOS)", "destination": "YOLA(YOL)" },
            { "origin": "MAIDUGURI(MIU)", "destination": "ABUJA(ABV)" },
            { "origin": "MAIDUGURI(MIU)", "destination": "KANO(KAN)" },
            { "origin": "MAIDUGURI(MIU)", "destination": "LAGOS(LOS)" },
            { "origin": "OWERRI(QOW)", "destination": "KANO(KAN)" },
            { "origin": "SOKOTO(SKO)", "destination": "ABUJA(ABV)" },
            { "origin": "SOKOTO(SKO)", "destination": "KANO(KAN)" },
            { "origin": "SOKOTO(SKO)", "destination": "LAGOS(LOS)" },
            { "origin": "YOLA(YOL)", "destination": "ABUJA(ABV)" },
            { "origin": "YOLA(YOL)", "destination": "KANO(KAN)" },
            { "origin": "YOLA(YOL)", "destination": "LAGOS(LOS)" },
            { "origin": "YOLA(YOL)", "destination": "SOKOTO(SKO)" }
        ],
        searchDump: JSON.stringify([
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "ABUJA(ABV)", "destination": "KATSINA(DKA)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "SOKOTO(SKO)" },
            { "origin": "ABUJA(ABV)", "destination": "YOLA(YOL)" },
            { "origin": "JEDDAH(JED)", "destination": "KANO(KAN)" },
            { "origin": "JEDDAH(JED)", "destination": "SOKOTO(SKO)" },
            { "origin": "JEDDAH(JED)", "destination": "YOLA(YOL)" },
            { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "JEDDAH(JED)" },
            { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
            { "origin": "KANO(KAN)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "KANO(KAN)", "destination": "OWERRI(QOW)" },
            { "origin": "KANO(KAN)", "destination": "SOKOTO(SKO)" },
            { "origin": "KANO(KAN)", "destination": "YOLA(YOL)" },
            { "origin": "KATSINA(DKA)", "destination": "ABUJA(ABV)" },
            { "origin": "KATSINA(DKA)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" },
            { "origin": "LAGOS(LOS)", "destination": "KATSINA(DKA)" },
            { "origin": "LAGOS(LOS)", "destination": "MAIDUGURI(MIU)" },
            { "origin": "LAGOS(LOS)", "destination": "SOKOTO(SKO)" },
            { "origin": "LAGOS(LOS)", "destination": "YOLA(YOL)" },
            { "origin": "MAIDUGURI(MIU)", "destination": "ABUJA(ABV)" },
            { "origin": "MAIDUGURI(MIU)", "destination": "KANO(KAN)" },
            { "origin": "MAIDUGURI(MIU)", "destination": "LAGOS(LOS)" },
            { "origin": "OWERRI(QOW)", "destination": "KANO(KAN)" },
            { "origin": "SOKOTO(SKO)", "destination": "ABUJA(ABV)" },
            { "origin": "SOKOTO(SKO)", "destination": "KANO(KAN)" },
            { "origin": "SOKOTO(SKO)", "destination": "LAGOS(LOS)" },
            { "origin": "YOLA(YOL)", "destination": "ABUJA(ABV)" },
            { "origin": "YOLA(YOL)", "destination": "KANO(KAN)" },
            { "origin": "YOLA(YOL)", "destination": "LAGOS(LOS)" },
            { "origin": "YOLA(YOL)", "destination": "SOKOTO(SKO)" }
        ]),
        "link": "maxair.com.ng",
        "fleet_size": 10,
        "hubs": ["Mallam Aminu Kano International Airport (KAN)"]
    },
    {
        "name": "OVERLAND AIRWAYS",
        "slug": "overland-airways",
        "company_name": "OVERLAND AIRWAYS LIMITED",
        "logo": "https://storage.aerocrs.com/299/system/logo-new-1.png",
        "details": "Overland Airways is based in Ikeja, the capital of Lagos State, at Murtala Muhammed International Airport.",
        "routes": [
            { "origin": "ABUJA", "destination": "AKURE" },
            { "origin": "ABUJA", "destination": "DUTSE" },
            { "origin": "ABUJA", "destination": "GOMBE" },
            { "origin": "ABUJA", "destination": "IBADAN" },
            { "origin": "AKURE", "destination": "ABUJA" },
            { "origin": "AKURE", "destination": "LAGOS" },
            { "origin": "DUTSE", "destination": "ABUJA" },
            { "origin": "GOMBE", "destination": "ABUJA" },
            { "origin": "IBADAN", "destination": "ABUJA" },
            { "origin": "IBADAN", "destination": "LAGOS" },
            { "origin": "ILORIN", "destination": "ABUJA" },
            { "origin": "ILORIN", "destination": "LAGOS" },
            { "origin": "JALINGO", "destination": "ABUJA" },
            { "origin": "LAGOS", "destination": "AKURE" },
            { "origin": "LAGOS", "destination": "IBADAN" },
            { "origin": "LAGOS", "destination": "ILORIN" }
        ],
        "searchDump": JSON.stringify([{ "origin": "ABUJA", "destination": "AKURE" },
        { "origin": "ABUJA", "destination": "DUTSE" },
        { "origin": "ABUJA", "destination": "GOMBE" },
        { "origin": "ABUJA", "destination": "IBADAN" },
        { "origin": "AKURE", "destination": "ABUJA" },
        { "origin": "AKURE", "destination": "LAGOS" },
        { "origin": "DUTSE", "destination": "ABUJA" },
        { "origin": "GOMBE", "destination": "ABUJA" },
        { "origin": "IBADAN", "destination": "ABUJA" },
        { "origin": "IBADAN", "destination": "LAGOS" },
        { "origin": "ILORIN", "destination": "ABUJA" },
        { "origin": "ILORIN", "destination": "LAGOS" },
        { "origin": "JALINGO", "destination": "ABUJA" },
        { "origin": "LAGOS", "destination": "AKURE" },
        { "origin": "LAGOS", "destination": "IBADAN" },
        { "origin": "LAGOS", "destination": "ILORIN" }]),
        "link": "overlandairways.com/en",
        "fleet_size": 9,
        "hubs": ["Murtala Muhammed International Airport, Lagos"]
    },
    {
        "name": "IBOM AIR",
        "slug": "ibom-air",
        "company_name": "AKWA IBOM INVESTMENT CORPORATION (AKICORP)",
        "logo": "https://www.ibomair.com/wp-content/uploads/2018/11/ibom-air-logo_small_trans.png",
        "details": "Ibom Air is a government-owned airline, owned by the Akwa Ibom State. The airline is based at Victor Attah International Airport, Uyo. It connects Akwa Ibom State with key destinations across Nigeria.",
        "routes": [
            { "origin": "ABUJA(ABV)", "destination": "CALABAR(CBQ)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "PORT-HARCOURT(PHC)" },
            { "origin": "ABUJA(ABV)", "destination": "UYO(QUO)" },
            { "origin": "ACCRA(ACC)", "destination": "LAGOS(LOS)" },
            { "origin": "CALABAR(CBQ)", "destination": "ABUJA(ABV)" },
            { "origin": "CALABAR(CBQ)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "ACCRA(ACC)" },
            { "origin": "LAGOS(LOS)", "destination": "CALABAR(CBQ)" },
            { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
            { "origin": "LAGOS(LOS)", "destination": "PORT-HARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "UYO(QUO)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "UYO(QUO)", "destination": "ABUJA(ABV)" },
            { "origin": "UYO(QUO)", "destination": "LAGOS(LOS)" }
        ],
        "link": "ibomair.com",
        "searchDump": JSON.stringify([
            { "origin": "ABUJA(ABV)", "destination": "CALABAR(CBQ)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "PORT-HARCOURT(PHC)" },
            { "origin": "ABUJA(ABV)", "destination": "UYO(QUO)" },
            { "origin": "ACCRA(ACC)", "destination": "LAGOS(LOS)" },
            { "origin": "CALABAR(CBQ)", "destination": "ABUJA(ABV)" },
            { "origin": "CALABAR(CBQ)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "ACCRA(ACC)" },
            { "origin": "LAGOS(LOS)", "destination": "CALABAR(CBQ)" },
            { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
            { "origin": "LAGOS(LOS)", "destination": "PORT-HARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "UYO(QUO)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "UYO(QUO)", "destination": "ABUJA(ABV)" },
            { "origin": "UYO(QUO)", "destination": "LAGOS(LOS)" }
        ]),
        "fleet_size": 8,
        "hubs": ["Victor Attah International Aiport, Uyo"]
    },
    {
        "name": "UNITED NIGERIA AIRLINES",
        "slug": "united-nigeria-airlines",
        "company_name": "UNITED NIGERIA AIRLINES LIMITED",
        "logo": "https://flyunitednigeria.com/wp-content/uploads/2022/08/UNITED-LOGO-min-1536x649.png",
        "details": "United Nigeria Airlines is a new private domestic airline in Nigeria. It was established in 2020 and received its Air Operators Certificate (AOC) in February 2021.",
        "routes": [
            { "origin": "ABUJA(ABV)", "destination": "ANAMBRA(ANA)" },
            { "origin": "ABUJA(ABV)", "destination": "ASABA(ABB)" },
            { "origin": "ABUJA(ABV)", "destination": "BENIN(BNI)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "ABUJA(ABV)", "destination": "SOKOTO(SKO)" },
            { "origin": "ABUJA(ABV)", "destination": "YENAGOA(BIA)" },
            { "origin": "ANAMBRA(ANA)", "destination": "ABUJA(ABV)" },
            { "origin": "ANAMBRA(ANA)", "destination": "LAGOS(LOS)" },
            { "origin": "ASABA(ABB)", "destination": "ABUJA(ABV)" },
            { "origin": "ASABA(ABB)", "destination": "LAGOS(LOS)" },
            { "origin": "BENIN(BNI)", "destination": "ABUJA(ABV)" },
            { "origin": "BENIN(BNI)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "ANAMBRA(ANA)" },
            { "origin": "LAGOS(LOS)", "destination": "ASABA(ABB)" },
            { "origin": "LAGOS(LOS)", "destination": "BENIN(BNI)" },
            { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
            { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" },
            { "origin": "LAGOS(LOS)", "destination": "OWERRI(QOW)" },
            { "origin": "LAGOS(LOS)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "SOKOTO(SKO)" },
            { "origin": "LAGOS(LOS)", "destination": "YENAGOA(BIA)" },
            { "origin": "OWERRI(QOW)", "destination": "ABUJA(ABV)" },
            { "origin": "OWERRI(QOW)", "destination": "LAGOS(LOS)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "SOKOTO(SKO)", "destination": "ABUJA(ABV)" },
            { "origin": "SOKOTO(SKO)", "destination": "LAGOS(LOS)" },
            { "origin": "YENAGOA(BIA)", "destination": "ABUJA(ABV)" },
            { "origin": "YENAGOA(BIA)", "destination": "LAGOS(LOS)" }
        ],
        "searchDump": JSON.stringify([
            { "origin": "ABUJA(ABV)", "destination": "ANAMBRA(ANA)" },
            { "origin": "ABUJA(ABV)", "destination": "ASABA(ABB)" },
            { "origin": "ABUJA(ABV)", "destination": "BENIN(BNI)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "KANO(KAN)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "ABUJA(ABV)", "destination": "SOKOTO(SKO)" },
            { "origin": "ABUJA(ABV)", "destination": "YENAGOA(BIA)" },
            { "origin": "ANAMBRA(ANA)", "destination": "ABUJA(ABV)" },
            { "origin": "ANAMBRA(ANA)", "destination": "LAGOS(LOS)" },
            { "origin": "ASABA(ABB)", "destination": "ABUJA(ABV)" },
            { "origin": "ASABA(ABB)", "destination": "LAGOS(LOS)" },
            { "origin": "BENIN(BNI)", "destination": "ABUJA(ABV)" },
            { "origin": "BENIN(BNI)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "ABUJA(ABV)" },
            { "origin": "KANO(KAN)", "destination": "LAGOS(LOS)" },
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "ANAMBRA(ANA)" },
            { "origin": "LAGOS(LOS)", "destination": "ASABA(ABB)" },
            { "origin": "LAGOS(LOS)", "destination": "BENIN(BNI)" },
            { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
            { "origin": "LAGOS(LOS)", "destination": "KANO(KAN)" },
            { "origin": "LAGOS(LOS)", "destination": "OWERRI(QOW)" },
            { "origin": "LAGOS(LOS)", "destination": "PORTHARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "SOKOTO(SKO)" },
            { "origin": "LAGOS(LOS)", "destination": "YENAGOA(BIA)" },
            { "origin": "OWERRI(QOW)", "destination": "ABUJA(ABV)" },
            { "origin": "OWERRI(QOW)", "destination": "LAGOS(LOS)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORTHARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "SOKOTO(SKO)", "destination": "ABUJA(ABV)" },
            { "origin": "SOKOTO(SKO)", "destination": "LAGOS(LOS)" },
            { "origin": "YENAGOA(BIA)", "destination": "ABUJA(ABV)" },
            { "origin": "YENAGOA(BIA)", "destination": "LAGOS(LOS)" }
        ]),
        link: "flyunitednigeria.com/"
    },
    {
        "name": "GREEN AFRICA AIRWAYS",
        "slug": "green-africa-airways",
        "company_name": "GREEN AFRICA AIRWAYS LIMITED",
        "logo": "https://gaassetstorage.s3.eu-west-2.amazonaws.com/svgassets/logo-green-africa-en.svg",
        "hubs": ["LAGOS MURTALA MUHAMMED INTERNATIONAL AIRPORT"],
        "details": "Green Africa Airways is one of the latest airlines in Nigeria. It launched in 2021. It is based in Lagos.",
        "routes": [
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "BENIN(BNI)" },
            { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
            { "origin": "LAGOS(LOS)", "destination": "IBADAN(IBA)" },
            { "origin": "LAGOS(LOS)", "destination": "ILORIN(ILR)" },
            { "origin": "LAGOS(LOS)", "destination": "OWERRI(QOW)" },
            { "origin": "LAGOS(LOS)", "destination": "PORT HARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "AKURE(AKR)" },
            { "origin": "ABUJA(ABV)", "destination": "AKURE(AKR)" },
            { "origin": "ABUJA(ABV)", "destination": "BENIN(BNI)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "IBADAN(IBA)" },
            { "origin": "ABUJA(ABV)", "destination": "ILORIN(ILR)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "PORT HARCOURT(PHC)" },
            { "origin": "AKURE(AKR)", "destination": "ABUJA(ABV)" },
            { "origin": "AKURE(AKR)", "destination": "LAGOS(LOS)" },
            { "origin": "AKURE(AKR)", "destination": "OWERRI(QOW)" },
            { "origin": "BENIN(BNI)", "destination": "ABUJA(ABV)" },
            { "origin": "BENIN(BNI)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "IBADAN(IBA)", "destination": "ABUJA(ABV)" },
            { "origin": "IBADAN(IBA)", "destination": "LAGOS(LOS)" },
            { "origin": "ILORIN(ILR)", "destination": "ABUJA(ABV)" },
            { "origin": "ILORIN(ILR)", "destination": "LAGOS(LOS)" },
            { "origin": "PORT HARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORT HARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "OWERRI(QOW)", "destination": "ABUJA(ABV)" },
            { "origin": "OWERRI(QOW)", "destination": "LAGOS(LOS)" }
        ],
        "searchDump": JSON.stringify([
            { "origin": "LAGOS(LOS)", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS)", "destination": "BENIN(BNI)" },
            { "origin": "LAGOS(LOS)", "destination": "ENUGU(ENU)" },
            { "origin": "LAGOS(LOS)", "destination": "IBADAN(IBA)" },
            { "origin": "LAGOS(LOS)", "destination": "ILORIN(ILR)" },
            { "origin": "LAGOS(LOS)", "destination": "OWERRI(QOW)" },
            { "origin": "LAGOS(LOS)", "destination": "PORT HARCOURT(PHC)" },
            { "origin": "LAGOS(LOS)", "destination": "AKURE(AKR)" },
            { "origin": "ABUJA(ABV)", "destination": "AKURE(AKR)" },
            { "origin": "ABUJA(ABV)", "destination": "BENIN(BNI)" },
            { "origin": "ABUJA(ABV)", "destination": "ENUGU(ENU)" },
            { "origin": "ABUJA(ABV)", "destination": "IBADAN(IBA)" },
            { "origin": "ABUJA(ABV)", "destination": "ILORIN(ILR)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS)" },
            { "origin": "ABUJA(ABV)", "destination": "OWERRI(QOW)" },
            { "origin": "ABUJA(ABV)", "destination": "PORT HARCOURT(PHC)" },
            { "origin": "AKURE(AKR)", "destination": "ABUJA(ABV)" },
            { "origin": "AKURE(AKR)", "destination": "LAGOS(LOS)" },
            { "origin": "AKURE(AKR)", "destination": "OWERRI(QOW)" },
            { "origin": "BENIN(BNI)", "destination": "ABUJA(ABV)" },
            { "origin": "BENIN(BNI)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "ENUGU(ENU)", "destination": "ABUJA(ABV)" },
            { "origin": "ENUGU(ENU)", "destination": "LAGOS(LOS)" },
            { "origin": "IBADAN(IBA)", "destination": "ABUJA(ABV)" },
            { "origin": "IBADAN(IBA)", "destination": "LAGOS(LOS)" },
            { "origin": "ILORIN(ILR)", "destination": "ABUJA(ABV)" },
            { "origin": "ILORIN(ILR)", "destination": "LAGOS(LOS)" },
            { "origin": "PORT HARCOURT(PHC)", "destination": "ABUJA(ABV)" },
            { "origin": "PORT HARCOURT(PHC)", "destination": "LAGOS(LOS)" },
            { "origin": "OWERRI(QOW)", "destination": "ABUJA(ABV)" },
            { "origin": "OWERRI(QOW)", "destination": "LAGOS(LOS)" }
        ]),
        "link": "www.greenafrica.com/"
    },
    {
        "name": "VALUEJET",
        "slug": "valuejet",
        "company_name": "FLY FOR VALUE",
        "logo": "https://flyvaluejet.com/images/valuejet-logo-white.png",
        "fleet_size": 3,
        "base": "Murtala Muhammed International Airport, Lagos",
        "routes": [
            { "origin": "ABUJA(ABV)", "destination": "BAUCHI(BCU)" },
            { "origin": "ABUJA(ABV)", "destination": "JOS(JOS)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS) MMA2" },
            { "origin": "BAUCHI(BCU)", "destination": "ABUJA(ABV)" },
            { "origin": "BAUCHI(BCU)", "destination": "LAGOS(LOS) MMA2" },
            { "origin": "JOS(JOS)", "destination": "ABUJA(ABV)" },
            { "origin": "JOS(JOS)", "destination": "LAGOS(LOS) MMA2" },
            { "origin": "LAGOS(LOS) MMA2", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS) MMA2", "destination": "BAUCHI(BCU)" },
            { "origin": "LAGOS(LOS) MMA2", "destination": "JOS(JOS)" }
        ],
        "searchDump": JSON.stringify([
            { "origin": "ABUJA(ABV)", "destination": "BAUCHI(BCU)" },
            { "origin": "ABUJA(ABV)", "destination": "JOS(JOS)" },
            { "origin": "ABUJA(ABV)", "destination": "LAGOS(LOS) MMA2" },
            { "origin": "BAUCHI(BCU)", "destination": "ABUJA(ABV)" },
            { "origin": "BAUCHI(BCU)", "destination": "LAGOS(LOS) MMA2" },
            { "origin": "JOS(JOS)", "destination": "ABUJA(ABV)" },
            { "origin": "JOS(JOS)", "destination": "LAGOS(LOS) MMA2" },
            { "origin": "LAGOS(LOS) MMA2", "destination": "ABUJA(ABV)" },
            { "origin": "LAGOS(LOS) MMA2", "destination": "BAUCHI(BCU)" },
            { "origin": "LAGOS(LOS) MMA2", "destination": "JOS(JOS)" }
        ]),
        "details": "ValueJet is a Nigerian airline that offers affordable flights within Nigeria. It is based at Murtala Muhammed International Airport in Lagos.",
        "link": "valuejet.com"
    }
];

export default aviation;
